export const SET_DATA = 'SET_DATA'
export const UPDATE_KEYWORDS = 'UPDATE_KEYWORDS'
export const UPDATE_TITLES = 'UPDATE_TITLES'
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD'

export const SET_ADS_PAGE_CACHE ='SET_ADS_PAGE_CACHE'
export const SET_TITLES_PAGE_CACHE ='SET_TITLES_PAGE_CACHE'

export const SET_TITLES_DATAGRID_CACHE ='SET_TITLES_DATAGRID_CACHE'

// export const UPDATE_MAX_ONE_TITLE_LENGHT = 'UPDATE_MAX_ONE_TITLE_LENGHT'
// export const UPDATE_MAX_TWO_TITLE_LENGHT = 'UPDATE_MAX_TWO_TITLE_LENGHT'
// export const UPDATE_DELETE_NEEDLESS = 'UPDATE_DELETE_NEEDLESS'
// export const UPDATE_ADD_NEEDLESS = 'UPDATE_ADD_NEEDLESS'
// export const UPDATE_TO_UPPER_FIRST_CASE = 'UPDATE_TO_UPPER_FIRST_CASE'
